### PR TITLE
Guard against usage errors that could cause data loss

### PR DESCRIPTION
**Pull request by joliss**
@stefanpenner, you like?

### CODE REVIEW

**Comment by joliss** [comment]
P.S. I miss mocha and chai :)

**Comment by stefanpenner** [comment]
> P.S. I miss mocha and chai :)

yes, i would prefer to live in a land of mocha. Should we port at some future time?

> @stefanpenner, you like?

LGTM, :shipit:

**Comment by joliss** [comment]
Great, merged and released in 0.3.0!

> yes, i would prefer to live in a land of mocha. Should we port at some future time?

Why not! It hasn't bothered me enough so far to rewrite the test suite, but I definitely wouldn't mind.

**Comment by stefanpenner** [comment]
> Why not! It hasn't bothered me enough so far to rewrite the test suite, but I definitely wouldn't mind.

If i feel compelled someday I will, although quite busy unclear when/if that might be.

**Pull request merged**
